version: '2'
services:
 selenoid:
  container_name: selenoid
  network_mode: bridge
  image: aerokube/selenoid
  volumes:
    - "$PWD:/etc/selenoid"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/docker/video:/opt/selenoid/video"
  environment:
    - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenium/video
  command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
  ports:
    - "4444:4444"

 selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

 web:
  container_name: web
  network_mode: bridge
  image: myweb
  expose:
   - "80"
  ports:
    - "80:80"